version: "3"
volumes:
  pg_data:
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5470:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
